# Generated by Django 5.1.1 on 2026-03-17 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                (
                    "visual_style",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[
                            ("9:16", "Portrait (9:16)"),
                            ("16:9", "Landscape (16:9)"),
                        ],
                        default="9:16",
                        max_length=5,
                    ),
                ),
                (
                    "clip_duration",
                    models.IntegerField(
                        choices=[(4, "4 seconds"), (6, "6 seconds"), (8, "8 seconds")],
                        default=8,
                    ),
                ),
                (
                    "num_clips",
                    models.IntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_aspect_ratio",
                    models.CharField(
                        choices=[
                            ("9:16", "Portrait (9:16)"),
                            ("16:9", "Landscape (16:9)"),
                        ],
                        default="9:16",
                        max_length=5,
                    ),
                ),
                (
                    "default_clip_duration",
                    models.IntegerField(
                        choices=[(4, "4 seconds"), (6, "6 seconds"), (8, "8 seconds")],
                        default=8,
                    ),
                ),
                (
                    "default_num_clips",
                    models.IntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "default_visual_style",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "video_quality",
                    models.CharField(
                        choices=[("720p", "720p"), ("1080p", "1080p"), ("4k", "4K")],
                        default="720p",
                        max_length=5,
                    ),
                ),
                (
                    "generation_speed",
                    models.CharField(
                        choices=[("quality", "Quality"), ("fast", "Fast")],
                        default="quality",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.CreateModel(
            name="Hook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_text", models.TextField(blank=True, default="")),
                (
                    "video_file",
                    models.FileField(blank=True, default="", upload_to="videos/hooks/"),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hook",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.IntegerField()),
                ("script_text", models.TextField(blank=True, default="")),
                (
                    "video_file",
                    models.FileField(blank=True, default="", upload_to="videos/"),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "generation_method",
                    models.CharField(
                        choices=[
                            ("text_to_video", "Text to Video"),
                            ("image_to_video", "Image to Video"),
                            ("frame_interpolation", "Frame Interpolation"),
                            ("extend_previous", "Extend from Previous Clip"),
                        ],
                        default="text_to_video",
                        max_length=30,
                    ),
                ),
                (
                    "first_frame",
                    models.ImageField(
                        blank=True, default="", upload_to="images/frames/"
                    ),
                ),
                (
                    "last_frame",
                    models.ImageField(
                        blank=True, default="", upload_to="images/frames/"
                    ),
                ),
                ("extension_count", models.IntegerField(default=0)),
                (
                    "generation_reference_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_number"],
                "unique_together": {("project", "sequence_number")},
            },
        ),
        migrations.CreateModel(
            name="ReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                ("image_file", models.ImageField(upload_to="images/references/")),
                ("label", models.CharField(max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "slot_number")},
            },
        ),
    ]
