# Generated by Django 5.1.15 on 2026-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.AddField(
            model_name="clip",
            name="selected_references",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ReferenceImage PKs selected for this clip.",
            ),
        ),
    ]
