# Generated by Django 5.1.15 on 2026-03-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_clip_selected_references"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="selected_references",
            field=models.JSONField(
                blank=True,
                db_default=models.Value("[]"),
                default=list,
                help_text="List of ReferenceImage PKs selected for this clip.",
            ),
        ),
    ]
